# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  versioning:
    permissions: write-all
    needs: build
    runs-on:
      ubuntu-latest
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    outputs:
      version: ${{ steps.latest_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Git Identity
        run: |
          git checkout main
          git fetch --all --tags
          git config --global user.email "antoniojosedonishung@gmail.com"
          git config --global user.name "Antonio Donis"
        
      - name: Changelog
        run: 'npx standard-version --message "[ci skip] chore(release): %s"'

      - name: Push changes
        run: git push --follow-tags --force origin main

      - id: latest_version
        name: Latest version
        run: python version.py >> $GITHUB_OUTPUT

  release-github:
    permissions: write-all
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.PERSONAL_TOKEN}}
          tag_name: v${{needs.versioning.outputs.version}}